### ISSUE TITLE
Debates are not showing on the debate page anymore.

### ISSUE THREAD

**Issue by Cranekick50** [Project-trigger/project-2#57]
Last push made us lose the ability to see the argument on the debate page.

**Comment by Cranekick50** [comment]
Executing (default): SELECT `id`, `user_id`, `incumbent_username`, `challenger_username`, `topic`, `incumbent_body`, `challenger_body`, `incumbent_votes`, `challenger_votes`, `comments`, `createdAt`, `updatedAt` FROM `Debates` AS `Debates`;
[0] Unhandled rejection SequelizeDatabaseError: Unknown column 'user_id' in 'field list'        
[0]     at Query.formatError (C:\Users\micha\GitHub\project-2\node_modules\sequelize\lib\dialects\mysql\query.js:244:16)
[0]     at Query.handler [as onResult] (C:\Users\micha\GitHub\project-2\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
[0]     at Query.execute (C:\Users\micha\GitHub\project-2\node_modules\mysql2\lib\commands\command.js:30:14)
[0]     at Connection.handlePacket (C:\Users\micha\GitHub\project-2\node_modules\mysql2\lib\connection.js:408:32)
[0]     at PacketParser.onPacket (C:\Users\micha\GitHub\project-2\node_modules\mysql2\lib\connection.js:70:12)
[0]     at PacketParser.executeStart (C:\Users\micha\GitHub\project-2\node_modules\mysql2\lib\packet_parser.js:75:16)
[0]     at Socket.<anonymous> (C:\Users\micha\GitHub\project-2\node_modules\mysql2\lib\connection.js:77:25)
